pub mod completion;
pub mod definition;
pub mod hover;
pub mod symbols;
pub mod formatting;
pub mod diagnostics;
pub mod references;
pub mod rename;
pub mod workspace_symbols;
pub mod signature_help;
pub mod code_actions;
pub mod semantic_tokens;
pub mod folding;
pub mod document_link;

pub use completion::provide_completion;
pub use definition::provide_definition_async;
pub use hover::provide_hover;
pub use symbols::provide_document_symbols;
pub use formatting::format_document;
pub use diagnostics::{validate_proto_file, create_parse_diagnostics};
pub use references::find_references;
pub use rename::{prepare_rename, rename};
pub use workspace_symbols::workspace_symbol;
pub use signature_help::provide_signature_help;
pub use code_actions::provide_code_actions;
pub use semantic_tokens::provide_semantic_tokens_full;
pub use folding::provide_folding_ranges;
pub use document_link::provide_document_links;
